name: pnpm Setup

description: 'Setup pnpm, Node.js, and install dependencies'

inputs:
  pnpm-version:
    description: 'pnpm version to install'
    required: false
    default: '10'
  node-version:
    description: 'Node.js version to use'
    required: false
    default: '24'
  frozen-lockfile:
    description: 'Use --frozen-lockfile flag'
    required: false
    default: 'false'

runs:
  using: 'composite'
  steps: # https://pnpm.io/continuous-integration#github-actions
    - uses: pnpm/action-setup@v4
      with:
        version: ${{ inputs.pnpm-version }}
        run_install: false

    - uses: actions/setup-node@v6
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'pnpm'

    - run: pnpm i ${{ inputs.frozen-lockfile == 'true' && '--frozen-lockfile' || '' }}
      shell: bash
